### ISSUE TITLE
problem with tmpjsobj

### ISSUE THREAD

**Issue by boykov** [Anoncheg1/Command-line-translator#8]
eab@kairos:~/git/dotemacs$ translate word
sed: невозможно прочитать tmpjsobj: Нет такого файла или каталога

/home/eab/.config/translate/tmpjsobj2:56
                print('Detected language: '+arr[8][0][0]); //detected language
                ^
ReferenceError: print is not defined
    at language_identification (/home/eab/.config/translate/tmpjsobj2:56:3)
    at Object.<anonymous> (/home/eab/.config/translate/tmpjsobj2:59:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3
.....

eab@kairos:~/git/dotemacs$ nodejs --version
v0.10.37
eab@kairos:~/git/dotemacs$ curl --version
curl 7.35.0 (x86_64-pc-linux-gnu) libcurl/7.35.0 OpenSSL/1.0.1f zlib/1.2.8 libidn/1.28 librtmp/2.3
eab@kairos:~/git/dotemacs$ html2text -version
This is html2text, version 1.3.2a

eab@kairos:~/git/dotemacs$ locale -a
C
C.UTF-8
en_AG
en_AG.utf8
en_AU.utf8
en_BW.utf8
en_CA.utf8
en_DK.utf8
en_GB.utf8
en_HK.utf8
en_IE.utf8
en_IN
en_IN.utf8
en_NG
en_NG.utf8
en_NZ.utf8
en_PH.utf8
en_SG.utf8
en_US.utf8
en_ZA.utf8
en_ZM
en_ZM.utf8
en_ZW.utf8
POSIX
ru_RU.cp1251
ru_RU.utf8
ru_UA.utf8

https://dl.dropboxusercontent.com/u/1897885/tmpjsobj2
https://dl.dropboxusercontent.com/u/1897885/tmpjsobj

**Comment by Anoncheg1** [comment]
fixed, check out
